site_name: "Ultima: Memento"

# Repository
repo_name: Ultima-Memento
repo_url: &github_url https://github.com/Jascen/ultima-memento
edit_uri: https://github.com/Jascen/Memento-Site/tree/main/docs

extra:
  client_download_link: https://drive.google.com/file/d/1ZyIFmwQ4d_wDhF0UtPgwMYEL0PWFwuvc/view?usp=sharing
  client_download_link_7z: https://drive.google.com/file/d/19jzs09O8MLc8BRSJoecR_skV8rDyCmEp/view?usp=sharing
  discord_guild_id: 1269722393757225033
  discord_invite_url: &discord_invite_url https://discord.gg/mu7aAbRyJf
  github_url: *github_url
  github_assets_url: https://github.com/Jascen/ultima-memento-assets/releases/download/data-files/data-files.zip
  is_offline: &is_offline !ENV [MEMENTO_SITE_OFFLINE, false]
  play_now_link: &play_now_link setup/desktop-client/#download-package
  play_now_link_offline: setup/desktop-client.html#download-package
  social:
    - icon: fontawesome/brands/discord
      link: *discord_invite_url
    - icon: fontawesome/brands/github
      link: *github_url

extra_css:
  - assets/stylesheets/chips.css

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/images/memento-m.png
  favicon: assets/images/memento-m.png
  features:
    # - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.action.edit
    - content.code.copy
  palette: 
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search
  - macros
  - offline:
      enabled: *is_offline

markdown_extensions:
  - attr_list
  - def_list
  - admonition
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

not_in_nav: |
  /setup/online-server-info.md

nav:
  - Home: index.md
  - <span style="color:var(--md-code-hl-color); font-weight:bold;">Play Now!</span>: *play_now_link
  - Getting Started:
    - Online Play: setup/online-play.md
    - Client:
      - Desktop: setup/desktop-client.md
      - Mobile: setup/mobile-client.md
    - Offline Play: setup/offline-play.md
  - Features:
    - New Game+:
      - Avatar's Ascent: features/avatars-ascent.md
      - Custom Races: features/custom-races.md
      - Temptations: features/temptations.md
    - Quality of Life: features/quality-of-life.md
  - Player Guide:
    - Welcome: guide/welcome.md
    - Gameplay Basics: guide/basics.md
    - Your Character:
      - Attributes: guide/attributes.md
      - Primary Skills: guide/skills-primary.md
      - Secondary Skills: guide/skills-secondary.md
    - Town: guide/town.md
    - The Art of Living: guide/art-of-living.md
    - Playing the Game: guide/playing-the-game.md
    - Things to Do:
      - Achievements: guide/achievements.md
      - Crafting: guide/crafting.md
      - Harvesting: guide/harvesting.md
      - Home Ownership: guide/home-ownership.md
      - Questing: guide/questing.md
      - Ships: guide/ships.md
    - Conclusion: guide/conclusion.md
    - Appendix:
      - Skill Descriptions: guide/appendix-skill-descriptions.md
      - Item Properties: guide/appendix-item-properties.md
      - Game Clients: guide/appendix-game-clients.md
  - Troubleshooting:
    - Client: issues/client.md
    - In game: issues/in-game.md
  - Contributing: contributing/index.md